### ISSUE TITLE
[Bug]: Generic error message upon searching on Firefox

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/insights#11]
### Issue description

Upon launching a search, I get an error message:

![image](https://github.com/user-attachments/assets/742fd37a-6418-4acb-8719-dc291ec0b3b7)

Upon further experimentation, this seems to be caused by the instant application of filters (the "Apply" button is gone. When I select one filter, the page immediately reload; if I select a second filter during the reload operation, the server often gets confused.

### Where did this happen?

[url](https://insights.sdg-innovation-commons.org/browse?search=&country=MKD&type=blog&type=document&page=1)

### What do you expect?

What do you expect?

### Platform

Insight

### What browsers are you seeing the problem on?

Firefox, Chrome

### Add any other relevant details

**Comment by this-pama** [comment]
Fixed.
