### ISSUE TITLE
[ENHANCEMENT]: Put the "Apply" button on the filter where it's easier to access

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/insights#2]
### What areas do you propose needs enhancement or improvement?

When filtering content by country, a very long list of countries opens. The "Apply" button gets pushed all the way down under the list, so once you have selected your country it's a lot of scrolling before you can execute the filter.

### Where is the current state/behavior?

(At maximum zoom out, only shows the list up to the letter L, the ribbon of countries is actually twice as tall as that, with the "Apply" button at the end)

![image](https://github.com/UNDP-Accelerator-Labs/insights/assets/1976806/720c97b3-67e3-4c24-af75-275bea81c620)

**Comment by this-pama** [comment]
You don't have to scroll all the way down. Clicking on anywhere outside the dropdown area collapses the dropdown and brings the 'Apply' button to your view area.
