### ISSUE TITLE
[Bug]: search does not work

### ISSUE THREAD

**Issue by myjyby** [UNDP-Accelerator-Labs/insights#8]
### Issue description

I am searching e.g. for the term "exploring", and while I know there are blogs that contain the word "exploring" nothing is retuned.

### Where did this happen?

insights platform

### What do you expect?

to see results after searching

### Platform

Global

### What browsers are you seeing the problem on?

Chrome

### Add any other relevant details

the insights platform is not available in the Platform dropdown list above

**Comment by this-pama** [comment]
Commits c4ce5f9 and 12d0c0e fixes the issue.
